/*
 * APILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package localhost9220;


public class Configuration {
    //The base Uri for API calls
    public static String baseUri = "http://localhost:9220";

}
